### ISSUE TITLE
Cache the downloaded JAR

### ISSUE THREAD

**Issue by tbroyer** [m273d15/java-format-action#1]
AFAICT, running the action will unconditionally download the google-java-format JAR from the Central repository. Not only does this take time (even though the JAR is rather small) but it adds an external dependency (Central has a good uptime record, but still), and is an absolute waste of computing resources (ecologically-speaking).

Maybe the tool could be cached into the (undocumented) `RUNNER_TOOL_CACHE` dir (see https://github.com/actions/toolkit/blob/5c894298f2f24441718eb049215aa6decd507193/packages/tool-cache/src/tool-cache.ts), or the action rewritten in JS to make use of the `@actions/tool-cache` package (and depending on users first setting up a Java environment through `actions/setup-java@v1`), or maybe using a Docker image coming with the tool rather than downloading it on each run?

See also google/google-java-format#288

**Comment by m273d15** [comment]
Thank you for your ideas. I have to rework the action. The image is currently build on each run. I am currently very busy, but I will check your recommendations asap. There is still room for improvements.

**Comment by m273d15** [comment]
I created a new version based on typescript using the tool-cache and environment by GitHub. This version is temporary available in via `- uses: m273d15/java-format-action@v1.1-rc`, but I will create a real release in the next days.
